spring:
  application:
    name: USER-SERVICE
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
