spring:
  application:
    name: PRODUCT-SERVICE
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8082
 # context-path: /productService #DO not add context for routing from eureka via zuul
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true