server:
  port: 8761
  
#We are telling the built-in Eureka Client not to register with ‘itself’, because our application should be acting as a server.  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false